# Generated by Django 5.0.3 on 2024-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SortModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.IntegerField()),
                ('Tact', models.IntegerField()),
                ('TimeComplete', models.IntegerField()),
            ],
        ),
    ]
