# Generated by Django 5.0.3 on 2024-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cic_api', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortmodel',
            name='Name',
            field=models.TextField(),
        ),
    ]
