# Generated by Django 5.0.3 on 2024-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cic_api', '0002_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortmodel',
            name='TimeComplete',
            field=models.FloatField(),
        ),
    ]
